-- 사용자 계정 생성
CREATE USER c##SERVER IDENTIFIED BY SERVER;

--접속 권한 및 테이블 생성 권한 부여
GRANT CONNECT, RESOURCE TO c##SERVER;

--테이블스페이스 설정
ALTER USER C##SERVER DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;