
DROP TABLE TEST;



CREATE TABLE TEST(
TNO NUMBER PRIMARY KEY,
TNAME VARCHAR2(100) NOT NULL,
TDATE DATE DEFAULT SYSDATE NOT NULL
);

INSERT INTO TEST VALUES (4,'홍길동',SYSDATE);
COMMIT;

SELECT * 
FROM TEST;
SELECT * FROM TEST WHERE TNO = 1;

DROP TABLE MEMBER;

CREATE TABLE MEMBER(
USER_NO NUMBER PRIMARY KEY, --회원번호
USER_ID VARCHAR2(30) NOT NULL UNIQUE,-- 아이디
USER_PWD VARCHAR2(30) NOT NULL,--비번
USER_NAME VARCHAR2(30) NOT NULL,--이름
GENDER CHAR(1) CHECK(GENDER IN('M','F')),--성별
AGE NUMBER, --나이
EMALL VARCHAR2(30), --이메일
PHONE CHAR(11), --핸드폰번호
ADDRESS VARCHAR2(100),--주소
HOBBY VARCHAR2(50),--취미
ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL--가입일
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원이름';
COMMENT ON COLUMN MEMBER.GENDER IS '성별(남/여)';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.CREATE_AT IS '회원가입일';

UPDATE MEMBER SET 
EMALL =? , PHONE=? , ADDRESS=? ,HOBBY=?
WHERE USER_ID=?;

CREATE SEQUENCE SEQ_USERNO
NOCACHE;

drop SEQUENCE SEQ_USERNO;
commit;
SELECT * FROM MEMBER WHERE USER_NAME LIKE '%동%' ;
--------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------
ALTER TABLE HUMAN
MODIFY (HUMAN_NUM NUMBER(10,2) DEFAULT 100 NOT NULL);

ALTER TABLE HUMAN
MODIFY (HUMAN_POWER NUMBER(10,2) DEFAULT 0 NOT NULL);

ALTER TABLE HUMAN
MODIFY (HUMAN_DEFENSIVE NUMBER(10,2) DEFAULT 0 NOT NULL);


DROP TABLE SHIELD;

--EQUIPMENTL
DROP TABLE HUMAN;
CREATE TABLE HUMAN(
HUMAN_NAME VARCHAR2(30) NOT NULL,--소드 이름
HUMAN_NUM NUMBER(10,2) DEFAULT 100 NOT NULL,--소드 강화 수치
HUMAN_POWER NUMBER DEFAULT 0 NOT NULL, --소드에 세긴 이니셜
HUMAN_DEFENSIVE NUMBER DEFAULT 0 NOT NULL,
HUMAN_SPECSLIST VARCHAR(50) DEFAULT 'N'
);
ALTER TABLE SHIELD
ADD (SHIELD_USE VARCHAR2(30) DEFAULT 'N' NOT NULL);


ALTER TABLE HUMAN
ADD CONSTRAINT chk_max3_specs
CHECK (HUMAN_SPECSLIST IS NULL OR REGEXP_COUNT(HUMAN_SPECSLIST, ',') + 1 <= 4);

INSERT INTO SHIELD 
VALUES ('실드', 0, '밥', SYSDATE, 'N');
CREATE TABLE SHIELD(
SHIELD_NAME VARCHAR2(30) NOT NULL,--소드 이름
SHIELD_NUM NUMBER DEFAULT 0 NOT NULL,--소드 강화 수치
SHIELD_INITIASL VARCHAR2(30), --소드에 세긴 이니셜
SHIELD_DATE DATE DEFAULT SYSDATE NOT NULL--소드 생성일

);

CREATE TABLE ARMOR(
ARMOR_NAME VARCHAR2(30) NOT NULL,--소드 이름
ARMOR_NUM NUMBER DEFAULT 0 NOT NULL,--소드 강화 수치
ARMOR_INITIASL VARCHAR2(30), --소드에 세긴 이니셜
ARMOR_DATE DATE DEFAULT SYSDATE NOT NULL--소드 생성일
);
-- JDBC 개인 실습용 sql


DROP TABLE BOOK;

CREATE TABLE BOOK(
    BOOK_ID   NUMBER         PRIMARY KEY,
    TITLE     VARCHAR2(100)   NOT NULL,
    AUTHOR    VARCHAR2(20),
    PUBLISHER VARCHAR2(50)
);

CREATE SEQUENCE SEQ_BOOK_ID;

INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID, '자바의 정석', '남궁성', '한빛');

INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID, '해리포터와 마법사의 돌', '최지원', '문학인');

INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID, '어린왕자', '토마스', '사람');

INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID, '1984', '조지 오웰', '열린');

INSERT INTO BOOK 
VALUES(SEQ_BOOK_ID, '데이터베이스개론', '허밍웨이', '한빛');




commit;