--1 계열 정보를 저장할 카테고리 테이블을 만들려고 한다, 다음과 같은 테이블을 작성하시오

CREATE TABLE TB_CATEGORY(
NAME VARCHAR2(10),
USE_TN CHAR(1) DEFAULT 'Y'
);

--2 과목 구분을 저장할 테이블을 만들려고한다. 다음과 같은 테이블 작성

CREATE TABLE TB_CLASS_TYPE
(
NO VARCHAR2(5) PRIMARY KEY,
NAME VARCHAR2(10)
);

--3 TB_CATAGORY 테이블의 NAME 컬럼에 PRIMARY KEY를 생성하시오
CREATE TABLE TB_CATAGORY
(
NAME VARCHAR2(5) PRIMARY KEY
);

--4 TB_CLASS_TYPE 테이블의 NAME 컬럼에 NULL값이 들어가지 않도록 속성을 변경하시오

ALTER TABLE TB_CLASS_TYPE
MODIFY NAME VARCHAR2(5) NOT NULL;