--1 학생이름과 주소지를표시하시오 헤더 / 학생이름 , 주소지 , 이름으로 오름차순

SELECT STUDENT_NAME AS "학생이름" ,STUDENT_ADDRESS "주소지"
FROM TB_STUDENT
ORDER BY STUDENT_NAME ASC;

--2 휴학중인 학생들의 이름과 주민번호를 나이가 적은 순서대로 화면에 출력
SELECT STUDENT_NAME AS "학생이름" ,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;

--3 주소지가 강원도나 경기도인 학생들중 1900년대 학번을 가진 학생들의 이름, 학번 ,주소 출력
--  이름의 오름차순 , 헤더 "학생이름" "학번" "거주지 주소" 
SELECT STUDENT_NAME AS "학생이름" , STUDENT_NO "학번" , STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT
WHERE (STUDENT_ADDRESS LIKE '%경기도%' OR STUDENT_ADDRESS LIKE '%강원도%')
AND SUBSTR(ENTRANCE_DATE,1,2) >'50' 
ORDER BY STUDENT_NAME;

-- 4 현재 법학과 교수 중 가장 나이가 많은 사람부터 이름을 확인 할 수 있는 SQL 문장을 작성
-- ( 법학과의 '학과코드' 는 학과 테이블을 조회해서 찾아내도록하자)
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NO = 005 
ORDER BY SUBSTR(PROFESSOR_SSN,1,2) ASC;

--5 2004년 2학기에 'C3118100' 과목을 수강한 학생들의 학점을 조회하려고 한다. 
-- 학점이 높은 학생부터 표시, 학점이 같으면 학번이 낮은학생부터 표시구문

SELECT STUDENT_NO, POINT
FROM TB_GRADE
WHERE CLASS_NO = 'C3118100'
  AND SUBSTR(TERM_NO, 1, 4) = '2004' 
  AND SUBSTR(TERM_NO, 5, 2) = '02'
ORDER BY POINT DESC, STUDENT_NO ASC;


--6 학생번호, 학생이름 , 학과이름을 / 학생이름으로 오름차순출력
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
ORDER BY STUDENT_NAME ASC;

--7 춘 기술대학교의 과목이름과 과목의 학과 이름을 출력하는 SQL문 작성하시오
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO);

--8 과목별 교수 이름을 찾으려고 한다, 과목이름과 교수 이름을 출력하는 SQL문을 작성하시오
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS USING(DEPARTMENT_NO);

--9 8번의 결과중 '인문사회' 계열에 속한 과목의 교수 이름을 찾으려한다 이에대한
-- 과목이름과 교수이름을 출력하는 SQL문 작성
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회' ;


-- 10. ' 음악학과 ' 학생들의 평점을 구하려고한다. 음악학과 학생들의 학번,학생이름,전체평점 을 출력
SELECT STUDENT_NO , STUDENT_NAME , ROUND(AVG(POINT),1)
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO , STUDENT_NAME
;

--11 학번이 A313047인 학생이 학교에 나오지않고있다. 지도교수에게 내용을 전달하기 위한
-- 학과이름 , 학생이름, 지도 교수 이름이 필요하다.
-- 단 출력헤더 "학과이름" "학생이름 " 지도교수이름" 출력
SELECT 
  D.DEPARTMENT_NAME AS "학과이름", 
  S.STUDENT_NAME AS "학생이름", 
  P.PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
JOIN TB_PROFESSOR P ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE S.STUDENT_NO = 'A313047';

-- 12 2007년도에 '인간관계론' 과목을 수강한 학생들 찾아 학생이름과 수강학기를 표시

SELECT STUDENT_NAME , TERM_NO 
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO)
WHERE CLASS_NAME = '인간관계론' AND SUBSTR(TERM_NO, 1, 4) = '2007' ;

--13 예체능 계열 과목 중 과목 담당교수를 한명도 배정받지못한 과목을 찾아 
-- 과목이름과 학광이름 출력

SELECT C.CLASS_NAME, D.DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON C.DEPARTMENT_NO = D.DEPARTMENT_NO
LEFT JOIN TB_CLASS_PROFESSOR CP ON C.CLASS_NO = CP.CLASS_NO
WHERE D.CATEGORY = '예체능' AND CP.CLASS_NO IS NULL;


-- 14 춘 기술대학교 서반아어학과 학생들으 ㅣ지도교수를 게시
-- 학생이름 지도교수를 찾고 , 만일 지도교수가없으면 "지도교수 미지정으로 표시
-- 헤더 학생이름 , 지도교수 고학번부터
SELECT 
  S.STUDENT_NAME AS "학생이름",
  NVL(P.PROFESSOR_NAME, '지도교수 미지정') AS "지도교수"
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
LEFT JOIN TB_PROFESSOR P ON S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
WHERE D.DEPARTMENT_NAME LIKE '%서반%'
ORDER BY S.STUDENT_NO DESC;



--15 휴학생이아닌 학생 중 평점이 4.0이상인 학생을 찾아 그 학생의 학번,이름,학과이름, 평정 출력
SELECT 
  S.STUDENT_NO, 
  S.STUDENT_NAME, 
  D.DEPARTMENT_NAME, 
  ROUND(AVG(G.POINT), 1) AS 평점
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
WHERE S.ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
HAVING AVG(G.POINT) >= 4.0
ORDER BY 평점 DESC;

--16 환경조경학과 전공과목들의 과목 별 평점을 파악할 수 잇는 SQL문을 작성하시오
SELECT CLASS_NO , CLASS_NAME , ROUND(AVG(POINT),1)
FROM TB_CLASS

JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING ( DEPARTMENT_NO )
WHERE DEPARTMENT_NAME = '환경조경학과'
GROUP BY CLASS_NO, CLASS_NAME;

-- 17 춘 기술대학교에 다니고 잇는 최경희 학생과 같은과학생들의 이름과 주소를 출력하는 SQL문 작성
SELECT STUDENT_NAME , STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (
SELECT DEPARTMENT_NO
FROM TB_STUDENT
WHERE STUDENT_NAME = '최경희'
)AND NOT (STUDENT_NAME = '최경희');

--- 18 국어국문학과에서 총 평점이 가장 높은학생의 이름과 학번을 표시하는 SQL문 작성
SELECT S.STUDENT_NAME, S.STUDENT_NO
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON S.DEPARTMENT_NO = D.DEPARTMENT_NO
JOIN TB_GRADE G ON S.STUDENT_NO = G.STUDENT_NO
WHERE D.DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NAME, S.STUDENT_NO
HAVING AVG(G.POINT) = (
  SELECT MAX(평균평점)
  FROM (
    SELECT AVG(POINT) AS 평균평점
    FROM TB_STUDENT S2
    JOIN TB_DEPARTMENT D2 ON S2.DEPARTMENT_NO = D2.DEPARTMENT_NO
    JOIN TB_GRADE G2 ON S2.STUDENT_NO = G2.STUDENT_NO
    WHERE D2.DEPARTMENT_NAME = '국어국문학과'
    GROUP BY S2.STUDENT_NO
  )
);
SELECT STUDENT_NAME, STUDENT_NO
FROM TB_STUDENT
JOIN TB_DEPARTMENT  USING (DEPARTMENT_NO)
JOIN TB_GRADE  USING (STUDENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
GROUP BY STUDENT_NAME, STUDENT_NO
HAVING AVG(POINT) = (
  SELECT MAX(평균평점)
  FROM (
    SELECT AVG(POINT) AS 평균평점
    FROM TB_STUDENT
    JOIN TB_DEPARTMENT  USING (DEPARTMENT_NO)
    JOIN TB_GRADE  USING (STUDENT_NO)
    WHERE DEPARTMENT_NAME = '국어국문학과'
    GROUP BY STUDENT_NO
  )
);

-- 19 춘 기술대학교의 "환경조경학과"가 속한 같은 계열 학과들의 학과 별 전공과목 평점을 
-- 파악하기 위한 적절한 SQL 문은? 
--- 헤더 "계열 학과명" , "전공평점" 평점은 소수 한자리까지 반올림
SELECT DEPARTMENT_NAME, ROUND(AVG(POINT), 1) AS "전공평점"
FROM TB_GRADE
JOIN TB_CLASS USING (CLASS_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE CLASS_TYPE LIKE '%전공%' AND CATEGORY = (
    SELECT CATEGORY
    FROM TB_DEPARTMENT
    WHERE DEPARTMENT_NAME = '환경조경학과'
  )
GROUP BY DEPARTMENT_NAME;
